### ISSUE TITLE
Unable to start the project

### ISSUE THREAD

**Issue by Ethella** [hcote/fortmatic-frontend-coding-challenge#1]
I wasn't able to make it run on my local env. 

I saw the `security/` folder has been ignored. But in either project, it requires having keys from the security folder.
Could you add them back to the project?
https://github.com/hcote/fortmatic-frontend-coding-challenge/blob/master/.gitignore#L27

**Comment by hcote** [comment]
Sorry about that, I just pushed a commit with the folders necessary.
ᐧ

**Comment by Ethella** [comment]
Thx, it works
